# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f1a19d329d289886f3829d9d58d2cb6b630c7d204d2676deeaf2a48fe2b7d06c2c3711971c13e32a7d51697b38a579e0fc58fc6237110e93555023957ba620

test:
  secret_key_base: 642e1400b6aea6bd6c7022f8e3bfc466c7201c32e35ab3f3106f4d253d867db10beabbcd30a2468a2b8fa755fbbc08eb7ea1973356b307d7431a7797587d9c97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
